### ISSUE TITLE
plan for maintenance or archiving

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/r-vscode-codespaces#11]
From Kathryn: @k-doering-NOAA 

I have a few ideas on a path forward

1) Edit the readme to link to repos with actively used codespace files and other resources that would stay up to date because they have active development, and let users know the files in this repo may be out of date;
2) Pass off maintenance to you and the new data science hire when they come on board.

**Comment by eeholmes** [comment]
I suggest plan 1 & 2. Edit the README to indicate that this repo is not being actively maintained and link to other resources.

One issue is that the rocker devcontainer docker images are still under heavy development. Nonetheless I like the the devcontainer.json files in this repo as they are relatively simple -- unlike some of the alternatives.

So I suggest these tasks:

- [ ] Add MAINTAINER.md with me (for now)
- [x] Add notice that this repo should be used for examples and that it is not being actively maintained.
- [x] Add link to Michael Ackridge's work on codespaces.

**Comment by k-doering-NOAA** [comment]
Thanks @eeholmes! I have this tagged on my list of things to do.

I can also link to some other examples of actively used codespaces that should remain up to date, including:
- [the FIMS codespace](https://github.com/NOAA-FIMS/FIMS/blob/main/.devcontainer/devcontainer.json)
- [the FIMS case studies codespace](https://github.com/NOAA-FIMS/case-studies/blob/main/.devcontainer/devcontainer.json)
- [the ghactions4r codespace](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.devcontainer/devcontainer.json)

All of these use the simple devcontainer.json approach
