### ISSUE TITLE
Create tidyverse and spatial set ups

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/r-vscode-codespaces#6]
I tested Rmd and qmd. Both work but the preview for qmd is not working. You can open in browser however.

- [ ] Add tidyverse? Will be bloated but seems like a common set of packages.

Or somehow have a files that user can run to add some curated set of typical packages? Somehow to make it easier for users to spin up a VM that should not require a whole lot of customizations.

- [ ] tidyverse
- [ ] mapping: sf, raster, other stuff
- [ ] ask R users to curate some lists?

**Comment by k-doering-NOAA** [comment]
@eeholmes luckily there are "tidyverse" and "geospatial" images as well: https://rocker-project.org/images/devcontainer/images.html

My question is what would be the best way to share this information (3 different setups, based on your needs)? Maybe a "how-to" that explains how to access the template while in a codespace would be better than maintaining a template repo?

**Comment by k-doering-NOAA** [comment]
also about quarto, did you uncomment these lines? https://github.com/nmfs-opensci/r-vscode-codespaces/blob/8ac9833aced08b3ecf6c1e3541eaa957095da2f0/.devcontainer/devcontainer.json#L17
Maybe including the vs code extension for quarto is also needed?

**Comment by eeholmes** [comment]
I think the "how-to" will be too much of a barrier if it involves edting the json file. It was confusing for me and I had to tweak the json file because the comments were not complete. Just things like needed some commas and I wanted to add tinytex.

So I think we should use the subfolder approach with a complete json file. Then give instructions about a) using a devcontainer in a subfolder or b) copying the desired json file in one of our subfolders into the .devcontainer/devcontainer.json file .

**Comment by eeholmes** [comment]
> also about quarto, did you uncomment these lines?
> 
> https://github.com/nmfs-opensci/r-vscode-codespaces/blob/8ac9833aced08b3ecf6c1e3541eaa957095da2f0/.devcontainer/devcontainer.json#L17
> 
> 
> Maybe including the vs code extension for quarto is also needed

Check out my pull-request and devcontainer file. I had to make a number of changes and it took an hour or so to get it all working. This is the devcontainer with Quarto working + has extensions.
https://github.com/nmfs-opensci/r-vscode-codespaces/blob/eli/.devcontainer/devcontainer.json

Here you can see the subfolders. Note `.devcontainer/devcontainer.json` is a copy of  .devcontainer/r-quarto/devcontainer.json` while the one in `r-base` is the one you had with just R.

**Comment by k-doering-NOAA** [comment]
closing this, as I think @eeholmes has done this elsewhere!
